/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package pkg305_projectv2;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author alano
 */

//Chating GUI + This class is (client) for the network
public class chatingPage extends javax.swing.JFrame {
     private static String msg = " ";

 /**
    /**
     * Creates new form P8
     */
    public chatingPage() throws IOException {
              initComponents();
              
        try {
            
         // (1) Create Socket obj   
            s = new Socket("127.0.0.1",8800);
            InputStream input = s.getInputStream();
            
            Scanner in = new Scanner (input);
            DoctorMSG = in.nextLine();
  
           in.close(); 
           input.close();
           

      }
         catch (UnknownHostException e) {
            System.err.println("Host not found");
        } catch (java.net.ConnectException e) {
            System.err.println("There are no connection at this port");
        } catch (IOException e) {
            System.err.println(e.getMessage());
        }
         
       
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">   
    //set up all gui components 
   private void initComponents() throws IOException {

         
       
        jPanel1 = new javax.swing.JPanel();
        sendButton = new javax.swing.JButton();
        messageSection = new javax.swing.JTextField();
        titel = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        MSGAreaPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        
        

         messageSection.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        messageSection.setForeground(new java.awt.Color(153, 153, 153));
        messageSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageSectionActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 242, 244));

        sendButton.setBackground(new java.awt.Color(255, 255, 255));
        sendButton.setForeground(new java.awt.Color(173, 69, 88));
        sendButton.setText("Send");
       
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public static String n = messageSection.getText();;
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                        
                try {
                    sendButtonActionPerformed(evt , m);
                } catch (IOException ex) {
                    Logger.getLogger(chatingPage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    
       
        titel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titel.setForeground(new java.awt.Color(173, 69, 88));
        titel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titel.setText("Doctor consultation");

        back.setBackground(new java.awt.Color(254, 242, 244));
        back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back.setText("<");
        back.addActionListener(new java.awt.event.ActionListener() {
            
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
                try {
                    
                    backActionPerformed(evt);
                } catch (IOException ex) {
                    Logger.getLogger(chatingPage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        MSGAreaPanel.setBackground(new java.awt.Color(255, 255, 255));

        msgTextArea.setColumns(20);
        msgTextArea.setRows(5);
        jScrollPane2.setViewportView(msgTextArea);

        javax.swing.GroupLayout MSGAreaPanelLayout = new javax.swing.GroupLayout(MSGAreaPanel);
        MSGAreaPanel.setLayout(MSGAreaPanelLayout);
        MSGAreaPanelLayout.setHorizontalGroup(
            MSGAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MSGAreaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );
        MSGAreaPanelLayout.setVerticalGroup(
            MSGAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MSGAreaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titel, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(messageSection, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sendButton))
                            .addComponent(MSGAreaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back)))
                .addGap(0, 16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back)
                .addGap(18, 18, 18)
                .addComponent(titel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MSGAreaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
             
       

        pack();
    }// </editor-fold>                         

  //take the message fron message section and display it on gui (send ) 
    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt , String n) throws IOException {                                           
        // TODO add your handling code here:
      
          chatingPage.this.msg=messageSection.getText();
          n = messageSection.getText();
        
        
         if ( !(msg.equalsIgnoreCase("bye"))) {
          
            msgTextArea.append("\n"+"PATIENT : "+msg);
            m = msgTextArea.getText();
           // System.out.println("m= " + m);
            msgTextArea.append("\n"+"DOCTOR : "+DoctorMSG);
           // System.out.println("50");
           
         }
         else {
            
             //System.out.println("1");
             
             s.close();
             
             //System.out.println("2");
        
         }
            
    }

    
public static String getmsg(){
    return m;
}
//get state when use go back to previuos page 
public static boolean getstate(){
    return backStat;
}
                                               

    private void messageSectionActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              
//back to previuos page ( consult a doctor )
    private void backActionPerformed(java.awt.event.ActionEvent evt) throws IOException {                                     
        // TODO add your handling code here:
        
        chatingPage.this.backStat= true;
        setStat();
        //System.out.println("back " + backStat);
        s.close();
        //backStat= true;
        Consult_a_doctor consult = new Consult_a_doctor();
        consult.setVisible(true);
        this.setVisible(false);
    } 
    
    public void setStat(){
        backStat = true ;
    }

   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chatingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chatingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chatingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chatingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
                
                try {
                    new chatingPage().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(chatingPage.class.getName()).log(Level.SEVERE, null, ex);
                }
                  
                
              
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel MSGAreaPanel;
    private javax.swing.JButton back;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    static javax.swing.JTextField messageSection;
    static javax.swing.JTextArea msgTextArea = new javax.swing.JTextArea();
    private javax.swing.JButton sendButton;
    private javax.swing.JLabel titel;            
    Socket s;
    String DoctorMSG ;
   
    static String m = " ";
    private static  boolean backStat = false ;
  
    
    // End of variables declaration                   
}


