/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package pkg305_projectv2;

import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author alano
 */
public class Medical_Encyclopedia extends javax.swing.JFrame {

    /**
     * Creates new form P2
     */
    public Medical_Encyclopedia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">   
    //this method setup all gui proprities 
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titel = new javax.swing.JLabel();
        HeadachButton = new javax.swing.JButton();
        Diabetes = new javax.swing.JButton();
        GastritisButton = new javax.swing.JButton();
        TonsillitisButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        ListButton = new javax.swing.JButton();
        profileButton = new javax.swing.JButton();
        chattingButton = new javax.swing.JButton();
        HomeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Medical Encyclopedia");
        setBackground(new java.awt.Color(204, 0, 0));
        setForeground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(254, 242, 244));

        Titel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Titel.setForeground(new java.awt.Color(192, 83, 102));
        Titel.setText("Medical Encyclopedia");

        HeadachButton.setBackground(new java.awt.Color(192, 83, 102));
        HeadachButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        HeadachButton.setForeground(new java.awt.Color(255, 255, 255));
        HeadachButton.setText("Headache");
        HeadachButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    HeadachButtonActionPerformed(evt);
                } catch (IOException ex) {
                    Logger.getLogger(Medical_Encyclopedia.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        Diabetes.setBackground(new java.awt.Color(192, 83, 102));
        Diabetes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Diabetes.setForeground(new java.awt.Color(255, 255, 255));
        Diabetes.setText("Diadetes");
        Diabetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    DiabetesActionPerformed(evt);
                } catch (IOException ex) {
                    Logger.getLogger(Medical_Encyclopedia.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        GastritisButton.setBackground(new java.awt.Color(192, 83, 102));
        GastritisButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GastritisButton.setForeground(new java.awt.Color(255, 255, 255));
        GastritisButton.setText("Gastritis");
        GastritisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    GastritisButtonActionPerformed(evt);
                } catch (IOException ex) {
                    Logger.getLogger(Medical_Encyclopedia.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        TonsillitisButton.setBackground(new java.awt.Color(192, 83, 102));
        TonsillitisButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TonsillitisButton.setForeground(new java.awt.Color(255, 255, 255));
        TonsillitisButton.setText("Tonsillitis");
        TonsillitisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    TonsillitisButtonActionPerformed(evt);
                } catch (IOException ex) {
                    Logger.getLogger(Medical_Encyclopedia.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        ListButton.setBackground(new java.awt.Color(254, 242, 244));
        ListButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/types.png"))); // NOI18N
        ListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListButtonActionPerformed(evt);
            }
        });

        profileButton.setBackground(new java.awt.Color(254, 242, 244));
        profileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/profile.png"))); // NOI18N
        profileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    profileButtonActionPerformed(evt);
                } catch (SQLException ex) {
                    Logger.getLogger(Medical_Encyclopedia.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        chattingButton.setBackground(new java.awt.Color(254, 242, 244));
        chattingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/chat.png"))); // NOI18N
        chattingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chattingButtonActionPerformed(evt);
            }
        });

        HomeButton.setBackground(new java.awt.Color(254, 242, 244));
        HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/home.png"))); // NOI18N
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chattingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(profileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profileButton)
                    .addComponent(chattingButton)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(HomeButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ListButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HeadachButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GastritisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Diabetes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TonsillitisButton, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Titel, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(Titel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HeadachButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Diabetes, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GastritisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TonsillitisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

//go to headach page when click button
    private void HeadachButtonActionPerformed(java.awt.event.ActionEvent evt) throws IOException {                                              
        // TODO add your handling code here:
        Headache H = new Headache();
        H.setVisible(true);

        this.setVisible(false);
    }                                             
//go to diabetes page when click on button 
    private void DiabetesActionPerformed(java.awt.event.ActionEvent evt) throws IOException {                                         
        // TODO add your handling code here:
        Diabetes D = new Diabetes();
        D.setVisible(true);

        this.setVisible(false);
    }                                        
//go to gastritis page when click on button 
    private void GastritisButtonActionPerformed(java.awt.event.ActionEvent evt) throws IOException {                                                
        // TODO add your handling code here:
        Gastritis G = new Gastritis();
        G.setVisible(true);

        this.setVisible(false);
    }                                               
//go to tonsillitis page when click on button 
    private void TonsillitisButtonActionPerformed(java.awt.event.ActionEvent evt) throws IOException {                                                  
        // TODO add your handling code here:
        Tonsillitis T = new Tonsillitis();
        T.setVisible(true);
        this.setVisible(false);
    }                                                 
//method to go to  list page when click on specific button
    private void ListButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        Medical_Encyclopedia M = new Medical_Encyclopedia ();
        M.setVisible(true);
        this.setVisible(false);
    }                                          
//method to go to  prfile page when click on specific button
    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {                                              
        // TODO add your handling code here:
        UserProfile profile = new UserProfile();
        profile.setVisible(true);
        this.setVisible(false);
    }                                             
//method to go to  chat(consult a doctor) page when click on specific button
    private void chattingButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
       Consult_a_doctor consult = new Consult_a_doctor();
        consult.setVisible(true);
        this.setVisible(false);
    }                                              
//method to go to  home page when click on specific button
    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:

        P10 p = new P10();
        p.setVisible(true);
        this.setVisible(false);
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Medical_Encyclopedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Medical_Encyclopedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Medical_Encyclopedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Medical_Encyclopedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new Medical_Encyclopedia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton Diabetes;
    private javax.swing.JButton GastritisButton;
    private javax.swing.JButton HeadachButton;
    private javax.swing.JButton HomeButton;
    private javax.swing.JButton ListButton;
    private javax.swing.JLabel Titel;
    private javax.swing.JButton TonsillitisButton;
    private javax.swing.JButton chattingButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton profileButton;
    // End of variables declaration 

    
}
