/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package pkg305_projectv2;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author alano
 */
public class Tonsillitis extends javax.swing.JFrame {

    /**
     * Creates new form P6
     */
    public Tonsillitis() throws IOException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">      
     //method contain all set up properties for gui component
    private void initComponents() throws FileNotFoundException, IOException {

        jPanel5 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        reasonSection = new javax.swing.JPanel();
        reason = new javax.swing.JLabel();
        typesSection = new javax.swing.JPanel();
        types = new javax.swing.JLabel();
        symptomsSection = new javax.swing.JPanel();
        symptoms = new javax.swing.JLabel();
        treatmentSection = new javax.swing.JPanel();
        treatment = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        
         reason1 =new javax.swing.JLabel();
        reason1.setText(readFileContent_Reason());
        
        type1 =new javax.swing.JLabel();
        type1.setText(readFileContent_Types());
        
        Symptoms1 =new javax.swing.JLabel();
        Symptoms1.setText(readFileContent_Symptoms());
        
        treatment1 =new javax.swing.JLabel();
        treatment1.setText(readFileContent_Treatment());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tonsillitis");

        jPanel5.setBackground(new java.awt.Color(254, 242, 244));

        title.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(192, 83, 102));
        title.setText("Tonsillitis");

        reasonSection.setBackground(new java.awt.Color(255, 255, 255));

        reason.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        reason.setForeground(new java.awt.Color(192, 83, 102));
        reason.setText("Reasons");

       
          javax.swing.GroupLayout reasonSectionLayout = new javax.swing.GroupLayout(reasonSection);
        reasonSection.setLayout(reasonSectionLayout);
        reasonSectionLayout.setHorizontalGroup(
            reasonSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reasonSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reasonSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reasonSectionLayout.createSequentialGroup()
                        .addComponent(reason, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 188, Short.MAX_VALUE))
                    .addComponent(reason1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        reasonSectionLayout.setVerticalGroup(
            reasonSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reasonSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reason)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reason1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        typesSection.setBackground(new java.awt.Color(255, 255, 255));

        types.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        types.setForeground(new java.awt.Color(192, 83, 102));
        types.setText("Types");

         javax.swing.GroupLayout TypesSectionLayout = new javax.swing.GroupLayout(typesSection);
        typesSection.setLayout(TypesSectionLayout);
        TypesSectionLayout.setHorizontalGroup(
            TypesSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TypesSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TypesSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TypesSectionLayout.createSequentialGroup()
                        .addComponent(types, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 171, Short.MAX_VALUE))
                    .addComponent(type1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        TypesSectionLayout.setVerticalGroup(
            TypesSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TypesSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(types)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(type1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        symptomsSection.setBackground(new java.awt.Color(255, 255, 255));

        symptoms.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        symptoms.setForeground(new java.awt.Color(192, 83, 102));
        symptoms.setText("Symptoms");

                javax.swing.GroupLayout SymptomsSectionLayout = new javax.swing.GroupLayout(symptomsSection);
        symptomsSection.setLayout(SymptomsSectionLayout);
        SymptomsSectionLayout.setHorizontalGroup(
            SymptomsSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SymptomsSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(symptoms, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
            .addGroup(SymptomsSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SymptomsSectionLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Symptoms1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        SymptomsSectionLayout.setVerticalGroup(
            SymptomsSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SymptomsSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(symptoms)
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(SymptomsSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SymptomsSectionLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(Symptoms1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(21, Short.MAX_VALUE)))
        );

        treatmentSection.setBackground(new java.awt.Color(255, 255, 255));

        treatment.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        treatment.setForeground(new java.awt.Color(192, 83, 102));
        treatment.setText("Treatment");

          javax.swing.GroupLayout treatmentSectionLayout = new javax.swing.GroupLayout(treatmentSection);
        treatmentSection.setLayout(treatmentSectionLayout);
        treatmentSectionLayout.setHorizontalGroup(
            treatmentSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(treatmentSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(treatment, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
            .addGroup(treatmentSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(treatmentSectionLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(treatment1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        treatmentSectionLayout.setVerticalGroup(
            treatmentSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(treatmentSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(treatment)
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(treatmentSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(treatmentSectionLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(treatment1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(21, Short.MAX_VALUE)))
        );

        back.setBackground(new java.awt.Color(254, 242, 244));
        back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back.setText("<");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back)
                .addGap(105, 105, 105)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 51, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(reasonSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typesSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(symptomsSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(treatmentSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(36, Short.MAX_VALUE)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(reasonSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(typesSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(symptomsSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(treatmentSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        
    
    //preform back movment to prevois page
    private void backActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        Medical_Encyclopedia back = new  Medical_Encyclopedia();
        
        back.setVisible(true);
        this.setVisible(false);
    }   
    
     //get types info from file and return it to print it in gui
   private static String readFileContent_Types() throws FileNotFoundException{
        
    StringBuilder content =new StringBuilder();
    String s=null;
    
    try{
        FileReader fr = new FileReader("tonsillities.txt");
        BufferedReader br = new BufferedReader(fr);
        
        while(br.ready()){
             if((s=br.readLine()).equalsIgnoreCase("Types")) { 
            while(!((s=br.readLine()).equalsIgnoreCase("Symptoms"))){ 
                 s+= "  "+"\n" ;
                  
                  content.append(s);
                 //content.append(s).append("\n");
                
          
            }  }
          else if((s.equalsIgnoreCase("Symptoms"))){
              break;
          }
            
            
        }
           br.close();
        fr.close();
    }catch(IOException ex) {
           ex.printStackTrace();}
    
    
    return content.toString();
    }
   
  //get reasons info from file and return it to print it in gui 
   private static String readFileContent_Reason(){
     
    StringBuilder content =new StringBuilder();
    String s=null;
    
    try{
        FileReader fr = new FileReader("tonsillities.txt");
        BufferedReader br = new BufferedReader(fr);
        
        while(br.ready()){
             if(!(s=br.readLine()).equalsIgnoreCase("Types"))  
               {
                 s+= "  "+"\n" ;
                 
                  //content.append(s);
                 content.append(s).append("\n");
             
           }
          else if((s.equalsIgnoreCase("Types"))){
              break;
          }
            
            
        }
        br.close();
        fr.close();
    }catch(IOException ex) {
           ex.printStackTrace();}
    
    
    return content.toString();
   }

   //get symptoms info from file and return it to print it in gui
private static String readFileContent_Symptoms() throws FileNotFoundException, IOException
{
   
    StringBuilder content =new StringBuilder();
    String s=null;
    
    try{
        FileReader fr = new FileReader("tonsillities.txt");
        BufferedReader br = new BufferedReader(fr);
        
        while(br.ready()){
             if((s=br.readLine()).equalsIgnoreCase("Symptoms")) { 
            while(!((s=br.readLine()).equalsIgnoreCase("Treatments"))){ 
                 s+= "  "+"\n" ;
                  
                  content.append(s);
               
                
          
            }
           
             
           }
          else if((s.equalsIgnoreCase("Treatments"))){
              break;
          }
            
            
        }
           br.close();
        fr.close();
    }catch(IOException ex) {
           ex.printStackTrace();}
    
    
    return content.toString();
}

//get treatment info from file and return it to print it in gui
private static String readFileContent_Treatment(){
    StringBuilder content =new StringBuilder();
    String s=null;
    int i=0;
    
    try{
        FileReader fr = new FileReader("tonsillities.txt");
        BufferedReader br = new BufferedReader(fr);
        
        
              
              while(br.ready()){
             if((s=br.readLine()).equalsIgnoreCase("Treatments")) { 
            while(!((s=br.readLine()).equalsIgnoreCase("end"))){ 
                 s+= "  "+"\n" ;
                 content.append(s).append("\n");
               
             
            }}
         }
        
        br.close();
        fr.close();
    }catch(IOException ex) {
           ex.printStackTrace();}
    
    
    return content.toString();
}

    
    
                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tonsillitis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tonsillitis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tonsillitis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tonsillitis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Tonsillitis().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Tonsillitis.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton back;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel reason;
    private javax.swing.JPanel reasonSection;
    private javax.swing.JLabel symptoms;
    private javax.swing.JPanel symptomsSection;
    private javax.swing.JLabel title;
    private javax.swing.JLabel treatment;
    private javax.swing.JPanel treatmentSection;
    private javax.swing.JLabel types;
    private javax.swing.JPanel typesSection;
    // End of variables declaration   
    
     private javax.swing.JLabel reason1;
    private javax.swing.JLabel type1;
    private javax.swing.JLabel Symptoms1;
    private javax.swing.JLabel treatment1;

}

    
